{{- range $cronJob := $.Values.app.cronJobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "web.fullname" $ }}-{{ $cronJob.name }}"
  labels:
    app.kubernetes.io/name: {{ include "web.name" $ }}
    helm.sh/chart: {{ include "web.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  schedule: "{{ $cronJob.schedule }}"
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ $cronJob.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: "{{ include "web.name" $ }}-{{ $cronJob.name }}"
            app.kubernetes.io/instance: {{ $.Release.Name }}
          annotations:
            ad.datadoghq.com/sync.logs: '[{"source":"{{ $.Release.Name}}","service":"api"}]'
        spec:
          imagePullSecrets:
          - name: {{ $.Values.cronImage.pullSecret }}
          restartPolicy: Never
          containers:
            - name: {{ $cronJob.name }}
              image: {{ $.Values.cronImage.repository }}:{{ $.Values.image.tag }}
              imagePullPolicy: {{ $.Values.cronImage.pullPolicy }}
              env:
                {{- toYaml $.Values.app.env | nindent 16 }}
              command:
                {{- toYaml $cronJob.command | nindent 16 }}

{{- end }}
