apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "web.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app.kubernetes.io/name: {{ include "web.name" . }}
    helm.sh/chart: {{ include "web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  activeDeadlineSeconds: 7200
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        ad.datadoghq.com/dbmigrate.logs: '[{"source":"{{ .Release.Name}}","service":"api"}]'
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: {{ .Values.image.repository }}:latest
          imagePullPolicy: Always
          env:
            {{- toYaml .Values.app.env | nindent 12 }}
          command:
            {{- toYaml .Values.app.migrateCommand | nindent 12 }}
