apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "web.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 60
  template:
    name: db-migrate
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "web.fullname" . }}
          command:
            - ./node_modules/.bin/typeorm
            - migration:run
