apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx
data:
  default.conf: |
    server {
      listen       80;
      server_name  _;

      auth_basic           "PG WEB";
      auth_basic_user_file /etc/nginx/htpasswd;

      location / {
        proxy_pass http://localhost:{{ .Values.app.containerPort }};
      }
    }
