{{- if eq .Values.istio.enabled true }}
{{- $relname := .Release.Name -}}
{{- $relns := .Release.Namespace -}}
{{- range .Values.istio.hosts }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $relname }}-{{ .host }}
  namespace: {{ $relns }}
spec:
  hosts:
  - {{ .host }}
  gateways:
  - {{ $relname }}
  http:
  - name: {{ $relname }}-route
    match:
{{- range .paths }}
    - uri:
        prefix: "{{ . }}"
{{- end }}
    route:
    - destination:
        host: {{ $relname }}.{{ $relns }}.svc.cluster.local
        port:
          number: 80
      weight: 100

---
{{- end }}
{{- end }}
